[package]
name = "polyhedron"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config= { version = "0.56.1" }
aws-sdk-transcribestreaming= { version = "0.34" }
aws-sdk-translate = "0.34"
aws-sdk-polly = "0.34"
clap = { version = "4.4" , features = ["derive"]}
tokio = {  version = "1.33" , features = ["full"] }
tokio-stream = "0.1"
async-stream = "0.3"
futures-util = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
serde_yaml = "0.9"
whisper-rs = {  version = "0.8" }
whisper-rs-sys = "0.6"
tracing = "0.1"
tracing-subscriber = "0.3"
lazy_static = "1.4"

[dependencies.poem]
version = "1.3"
features = ["websocket", "static-files"]

[target.aarch64-apple-darwin.dependencies.whisper-rs]
features = ["coreml"]