[package]
name = "polyhedron"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config= { version = "0.56.1" }
aws-sdk-transcribestreaming= { version = "0.33.0" }
aws-sdk-translate = "0.33.0"
aws-sdk-polly = "0.33.0"
clap = { version = "4.4.6" , features = ["derive"]}
hound = "3.5.1"
tokio = {  version = "1.33.0" , features = ["full"] }
tokio-stream = "0.1.14"
bytes = "1.0.1"
async-stream = "0.3.5"
tracing-subscriber = "0.3.17"
futures-util = "0.3.28"
#symphonia-codec-pcm = "0.5.3"
#symphonia-format-mkv = "0.5.3"
symphonia = { version = "0.5.3", features = ["mkv", "pcm"] }
serde = { version = "1.0.189", features = ["derive"] }

[dependencies.poem]
version = "1.3.58"
features = ["websocket", "static-files"]
