[package]
name = "polyhedron"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
async-stream = "0.3"
aws-config = "0.56"
aws-sdk-transcribestreaming = "0.34"
aws-sdk-translate = "0.34"
aws-sdk-polly = "0.34"
config = "0.13"
futures-util = "0.3"
once_cell = "1.18"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
tokio = { version = "1.33", features = ["macros", "rt-multi-thread", "sync"] }
tokio-stream = "0.1"
tracing = "0.1"
tracing-subscriber = "0.3"
whisper-rs = "0.8"
whisper-rs-sys = "0.6"

[dependencies.poem]
version = "1.3"
features = ["websocket", "static-files"]

[target.aarch64-apple-darwin.dependencies.whisper-rs]
version = "0.8"
features = ["coreml"]

[target.aarch64-apple-darwin.dependencies.whisper-rs-sys]
version = "0.6"


[target.x86_64-unknown-linux-gnu.dependencies.whisper-rs]
features = ["cuda"]

[target.aarch64-unknown-linux-gnu.dependencies.whisper-rs]
features = ["cuda"]
