[package]
name = "polyhedron"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config= { version = "0.56.1" }
aws-sdk-transcribestreaming= { version = "0.33.0" }
aws-sdk-translate = "0.33.0"
aws-sdk-polly = "0.33.0"
clap = { version = "4.4.6" , features = ["derive"]}
tokio = {  version = "1.33.0" , features = ["full"] }
tokio-stream = "0.1.14"
async-stream = "0.3.5"
futures-util = "0.3.28"
serde = { version = "1.0.189", features = ["derive"] }
serde_json = { version = "1.0.107" }
serde_yaml = "0.9.25"
whisper-rs = {  version = "0.8.0" }
whisper-rs-sys = "0.6.1"
tracing = "0.1.40"
tracing-subscriber = "0.3.17"
lazy_static = "1.4.0"
tokio-postgres = "0.7.8"
chrono = "0.4.26"

[dependencies.poem]
version = "1.3.58"
features = ["websocket", "static-files"]

[target.aarch64-apple-darwin.dependencies.whisper-rs]
features = ["coreml"]