server:
    port: 8080
    host: ::1
whisper:
    length_ms: 10000
    keep_ms: 200
    step_ms: 5000
    model: "models/ggml-base.bin"
    max_prompt_tokens: 128
    params:
        #n_threads: 4
        max_tokens: 0
        audio_ctx: 0
        speed_up: false
        single_segment: false
        translate: false
        no_fallback: false
        temperature_inc: -1.0
        print_special: false
        print_progress: false
        print_realtime: false
        no_context: false
        no_timestamps: false
        tinydiarize: false
        language: "en"